name: pre-commit (all files on push)

on:
  push:
    branches: [main, post-commit-test]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      with:
        extra_args: --color=always --all-files
